# Generated by Django 5.1.4 on 2025-01-22 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemRegister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the inventory item.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "item_id",
                    models.CharField(
                        editable=False,
                        help_text="Automatically generated unique identifier for the item.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of the item.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The cost per unit of the item.",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="The quantity of this inventory item (must be 1 or greater).",
                    ),
                ),
                (
                    "remarks",
                    models.CharField(
                        default="Perfect",
                        help_text="Remarks on the item's condition (max 100 characters).",
                        max_length=100,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="The description of the inventory item, pre-filled from ItemRegister.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "year",
                    models.PositiveIntegerField(
                        default=2025, help_text="Year of the inventory"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user managing this inventory item.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "item_id",
                    models.ForeignKey(
                        help_text="The standardized item from the Register.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inventory_items",
                        to="core.itemregister",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        help_text="The office this inventory item is assigned to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory_items",
                        to="core.office",
                    ),
                ),
            ],
            options={
                "ordering": ["item_id__name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1)), name="quantity_gte_1"
                    )
                ],
                "unique_together": {("user", "office", "item_id", "year")},
            },
        ),
    ]
