# Generated by Django 5.1.3 on 2025-01-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="A brief description of the inventory item.",
                null=True,
            ),
        ),
    ]
