# Generated by Django 5.1.3 on 2025-01-10 09:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_inventoryitem_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inventoryitem",
            name="remarks",
            field=models.CharField(
                help_text="Remarks on the item's condition (max 100 characters).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="Optional description of the inventory item (max 100 characters).",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=0,
                help_text="The quantity of this inventory item (must be 1 or greater).",
            ),
        ),
        migrations.AddConstraint(
            model_name="inventoryitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="quantity_gte_1"
            ),
        ),
    ]
