# Generated by Django 5.1.3 on 2025-01-11 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_office_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="office",
            name="user",
        ),
    ]
