# Generated by Django 5.1.4 on 2025-01-16 07:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_inventoryitem_remarks_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the inventory item.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "stock_id",
                    models.CharField(
                        editable=False,
                        help_text="Automatically generated unique identifier for the item.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional description of the item.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        help_text="The cost per unit of the item.",
                        max_digits=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="inventoryitem",
            options={"ordering": ["item_id__name"]},
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="year",
            field=models.PositiveIntegerField(
                default=2025, help_text="Year of the inventory"
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="description",
            field=models.CharField(
                blank=True,
                help_text="The description of the inventory item, pre-filled from ItemRegistry.",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="remarks",
            field=models.CharField(
                default="Perfect",
                help_text="Remarks on the item's condition (max 100 characters).",
                max_length=100,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="inventoryitem",
            name="item_id",
            field=models.ForeignKey(
                default="null",
                help_text="The standardized item from the registry.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventory_items",
                to="core.itemregistry",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="inventoryitem",
            unique_together={("user", "office", "item_id", "year")},
        ),
        migrations.RemoveField(
            model_name="inventoryitem",
            name="name",
        ),
    ]
