# Generated by Django 5.1.3 on 2025-01-10 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_remove_customuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                ],
                default="staff",
                help_text="The role assigned to the user (e.g., admin, staff).",
                max_length=20,
            ),
        ),
    ]
